### ISSUE TITLE
[osx] Application opens with GUI beyond the screen

### ISSUE THREAD

**Issue by vorg** [dariomanesku/cmftStudio#1]
OSX 10.10.3, rMBP, Screen resolution 1680x1050

![screen shot 2015-03-06 at 11 13 15](https://cloud.githubusercontent.com/assets/171001/6524479/cd85b5ba-c3f1-11e4-9fed-0dd428d17c7a.jpg)

I can fix it by 'maximizing' (not fullscreen) the window by double clicking the title bar.

**Comment by dariomanesku** [comment]
Here: https://github.com/dariomanesku/cmftStudio#requirements

The interface cannot be trivially scaled down. It either fits the screen or it doesn't.
I might do something about that in the future, but for now it is what it is.

It would be great if you could post here a screenshot to see how it looks when the window is maximized.

**Comment by vorg** [comment]
When maximized it not optimal (scrollbars) but works just fine.
![screen shot 2015-03-06 at 21 00 24](https://cloud.githubusercontent.com/assets/171001/6536258/fe21c39c-c443-11e4-872c-26716510420a.jpg)

**Comment by dariomanesku** [comment]
I added full screen support. It can be switched from the interface or with 'Command + F'.
That's all I could do for now, scaling down the interface might come on a different occasion.

**Comment by dariomanesku** [comment]
I added support for lower resolution screens, the interface should now scale down appropriately.
