### ISSUE TITLE
Files browser

### ISSUE THREAD

**Issue by Spirou4D** [dariomanesku/cmftStudio#10]
Hi Mario,

Thanks for your very good application! I have a little problem here in France because we had letters with accents and they don't appear in the file browser.
Is it possible to add unicode for the files browser, please?

Congratulations.
Patrick D.

**Comment by dariomanesku** [comment]
It's Dario. Here: https://github.com/dariomanesku/cmftStudio/commit/e407381e601feedb34803d86f07a63de1d4c5fd0, but it'll only works on Windows I guess. This is what cmftStudio uses for listing files: https://github.com/cxong/tinydir.

**Comment by Spirou4D** [comment]
Ok! Thks Weird, it would must show/read unicode linux file name!

**Comment by Spirou4D** [comment]
See here Dario (Sorry I make a mistake with your name!!!)
http://storage3.static.itmages.com/i/16/0822/h_1471879963_9169820_94e23546cf.jpeg

**Comment by dariomanesku** [comment]
Good. It's not perfect, but it's usable, unicode files/folders are visible.

**Comment by Spirou4D** [comment]
Ho you are right, I must yet do tests to save and load.
It's may be only a mistake of the display of names.
byebye
Patrick
