### ISSUE TITLE
Cant Save 16 Bit DDS

### ISSUE THREAD

**Issue by DougChism** [dariomanesku/cmftStudio#11]
When trying to save a 16-bit format, it saves as a 32-bit format that does not load correctly through D3DX or the DDS texture tool.

**Comment by dariomanesku** [comment]
Yeah, there is a problem with DDS, I don't know exactly where. Here's the code that saves DDS: https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L4869

For now you should use https://community.imgtec.com/developers/powervr/tools/pvrtextool/ and/or GIMP + https://code.google.com/archive/p/gimp-dds to workaround the problem.

**Comment by Raikiri** [comment]
There is indeed a problem with dds float32 exporter. Exported file can be opened by cmft itself but cannot be opened by any other tools. 

Unfortunately PVRTexTool is unable to save cubemaps and gimp-dds is unable to load panoramic images. Basically cmft looks like the perfect solution for my case (panoramic .hdr -> float32 cubemap dds conversion) but unfortunately produced image can only be loaded by cmft itself.

**Comment by Raikiri** [comment]
All right, I have found a fix for my case. I have checked an exported skybox that worked for me(from AMD CubeMapGen) and it had a different m_fourcc field. By replacing DDS_DX10 with a magic number 116 it worked for me. So the fix is to replace this:

```

    static const DdsPixelFormat s_ddsPixelFormat[] =
    {
        { sizeof(DdsPixelFormat), DDPF_RGB,    D3DFMT_R8G8B8,    24, 0x00ff0000, 0x0000ff00, 0x000000ff, 0x00000000 }, //BGR8
        { sizeof(DdsPixelFormat), DDPF_RGBA,   D3DFMT_A8B8G8R8,  32, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //BGRA8
        { sizeof(DdsPixelFormat), DDPF_FOURCC, DDS_DX10,         64, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //RGBA16
        { sizeof(DdsPixelFormat), DDPF_FOURCC, DDS_DX10,         64, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //RGBA16F
        { sizeof(DdsPixelFormat), DDPF_FOURCC, 116,              128,0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //RGBA32F
    };
```
with this:
```

    static const DdsPixelFormat s_ddsPixelFormat[] =
    {
        { sizeof(DdsPixelFormat), DDPF_RGB,    D3DFMT_R8G8B8,    24, 0x00ff0000, 0x0000ff00, 0x000000ff, 0x00000000 }, //BGR8
        { sizeof(DdsPixelFormat), DDPF_RGBA,   D3DFMT_A8B8G8R8,  32, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //BGRA8
        { sizeof(DdsPixelFormat), DDPF_FOURCC, 116,              64, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //RGBA16
        { sizeof(DdsPixelFormat), DDPF_FOURCC, 116,              64, 0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //RGBA16F
        { sizeof(DdsPixelFormat), DDPF_FOURCC, 116,              128,0x00ff0000, 0x0000ff00, 0x000000ff, 0xff000000 }, //RGBA32F
    };
```
apparently this thing also omits DX10 header but it works just fine for D3DX loader that I'm using it for.
