### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by guycalledfrank** [dariomanesku/cmftStudio#18]
Apparently it wasn't tested with anything except 1920x1080? (Win7)

![cmfts](https://user-images.githubusercontent.com/7008423/29497359-0e18a918-85ef-11e7-8603-c85bad4a8df1.jpg)

UPD: Enlarging the window fixes this problem

**Comment by dariomanesku** [comment]
Yeah, UI and scaling wasn't really properly addressed. If enlarging the window fixes this problem - that's it. :)
