### ISSUE TITLE
Does cmftStudio create diffuse irradiance / specular cube map?

### ISSUE THREAD

**Issue by bitinn** [dariomanesku/cmftStudio#19]
Sorry for this newbie question:

- I am trying to figure out if cmftStudio does what [IBLBaker](https://github.com/derkreature/IBLBaker) can do.

- In particular, I am trying to understand if the "irradiance" and "radiance" cube map it creates are the same as "diffuse irradiance" and "specular".

- While the output DDS cube map looks fine, for some reasons they appear way too bright when applied in Maya.

For a comparison:

The diffuse cube map Maya uses by default seem rather faint.

<img width="850" alt="screen shot 2017-09-07 at 00 14 40" src="https://user-images.githubusercontent.com/1484279/30122657-cd51594a-9361-11e7-90ce-73ac007f9e40.png">

<img width="853" alt="screen shot 2017-09-07 at 00 14 45" src="https://user-images.githubusercontent.com/1484279/30122683-e8e21da2-9361-11e7-95ae-dbc641171eea.png">

And thus they result in quite different rendering.

<img width="855" alt="screen shot 2017-09-07 at 00 14 54" src="https://user-images.githubusercontent.com/1484279/30122700-fd50bb86-9361-11e7-8edf-efd9cf2fd6e3.png">

<img width="842" alt="screen shot 2017-09-07 at 00 15 05" src="https://user-images.githubusercontent.com/1484279/30122704-0137c168-9362-11e7-962b-42b54b77667e.png">

I believe Maya's [Stinyray PBS material does use PBR IBL](https://knowledge.autodesk.com/support/maya-lt/learn-explore/caas/CloudHelp/cloudhelp/2017/ENU/MayaLT/files/GUID-04F2FFA5-1797-4FEF-8A52-AEE00C47224E-htm.html), so my question is, are there somehow multiple implementation of IBL? Why would Maya requires a faint Diffuse and Specular map?

**Comment by bitinn** [comment]
The reason: they use RGBM (pretty sure cmftStudio doesn't support in GUI yet.)

**Comment by dariomanesku** [comment]
https://github.com/dariomanesku/cmft does support rgbm from the command line if you really need it. If my memory serves me well - rgbm was added later to cmft and the option didn't get exposed in the end in cmftStudio's GUI.
