### ISSUE TITLE
Rotate the cubemap?

### ISSUE THREAD

**Issue by bitinn** [dariomanesku/cmftStudio#20]
Hi,

Just wondering if there is a solution to **rotating the HDR environment map and then generate a cubemap**. Seems like Lys can do this, not sure cmftStudio currently offers it.

For some weird reasons Maya wants an IBL cubemap with Y+ in the middle, eg:

<img width="421" alt="screen shot 2017-12-28 at 03 36 39" src="https://user-images.githubusercontent.com/1484279/34413780-7a3eb92e-ec20-11e7-892e-7d0b810140b0.png">

But I only have panorama HDR or standard cubemap with Z+/X+ in the middle. Hence the question.

(Happy Holiday!)

**Comment by dariomanesku** [comment]
No, unfortunately rotation is not exposed in the cmftStudio UI.
