### ISSUE TITLE
DDS codec generation for babylonis

### ISSUE THREAD

**Issue by electroheadfx** [dariomanesku/cmftStudio#21]
Hey, I don't know if its an issue, but I got an error in babylonJS with DDS load : Unsupported FourCC code: DX10

is it possible to lower the DX compression to 3, or 1 ?

Maybe Iam wrong with the DDS setting. Thanks in advance

**Comment by dariomanesku** [comment]
You're right, DDS export has some compatibility issues. You can perhaps try to use GIMP or PVRTexTool to re-export images before using them with babylonJS.

**Comment by electroheadfx** [comment]
Thanks for your answer dariomanesku but I found the workflow with Cmft in bash command line: https://github.com/dariomanesku/cmft
it works great

**Comment by dariomanesku** [comment]
Yeah, cmft has some DDS fixes that haven't been brought to cmftStudio.
Glad that it works.
