### ISSUE TITLE
Switch to Arcball Camera

### ISSUE THREAD

**Issue by vorg** [dariomanesku/cmftStudio#3]
Is there a way to rotate model? The fluid drag + shift rotate are quite bad.

Arcball camera controller would be much more user friendly.

Example
http://marcinignac.com/experiments/ssao-gamma/demo/

**Comment by dariomanesku** [comment]
Y axis rotation is done by: `middle click + drag` or, alternatively on OS X, `shit + left click + drag`.
I added this: https://github.com/dariomanesku/cmftStudio#help

X axis rotation is only available for spheres scene. Spheres -> Model -> Manual control.

I had a camera implementation that was behaving just like the one on the link, but the problem with it was that the model was always centered at origin and you can't move it in space. Than, as a solution to that, I changed camera behavior to this.

It may feel weird at first, like whenever switching between different 3D software, but when you get used to it I think it's fine. I'm not sure how well it behaves on a trackpad though, I haven't tried that.
