### ISSUE TITLE
[Linux] Window doesn't draw past 1080p

### ISSUE THREAD

**Issue by friesencr** [dariomanesku/cmftStudio#4]
In the image you can see that the window things it is bigger than 1080 but doesn't draw outside it.

![cmft_gt_1080_bug](https://cloud.githubusercontent.com/assets/105460/6568639/1150145c-c6a9-11e4-9b2a-02a058971b83.png)

Thanks,
Chris

**Comment by dariomanesku** [comment]
Try going full screen (Ctrl+F) and back ?
Are you using the latest binary 'cmftStudio - Linux 64bit - Updated on: 9. Mar, 2015.' ?

**Comment by friesencr** [comment]
I am using https://github.com/dariomanesku/cmftStudio/commit/f26508dd246c225ba3878e017c7b2cbd8dcdd96c
compiled from source.

Ctrl+F doesn't engage fullscreen nor does clicking the fullscreen button in the options.

**Comment by dariomanesku** [comment]
The mentioned binary is built with SDL and therefore window management and full screen work good. The X11 version is still not fixed.

If you want to try and build cmftStudio with SDL, just add '--with-sdl' here: https://github.com/dariomanesku/cmftStudio/blob/master/Makefile#L36

**Comment by friesencr** [comment]
That fixed it :metal:

**Comment by dariomanesku** [comment]
:+1:
