### ISSUE TITLE
Wrong path separator on OSX

### ISSUE THREAD

**Issue by vorg** [dariomanesku/cmftStudio#5]
You are using `\` but should be `/`

![screen shot 2015-03-10 at 19 37 47](https://cloud.githubusercontent.com/assets/171001/6581075/01de0e6e-c76e-11e4-96ca-fc902a14111b.png)
 
so I get files with folder name in them on save

![screen shot 2015-03-10 at 21 40 47](https://cloud.githubusercontent.com/assets/171001/6581098/2825add4-c76e-11e4-9ee7-f8d387fefcb5.png)

**Comment by dariomanesku** [comment]
I solved the problem but I haven't updated the binaries yet. It'll happen in a few days after I finish with downscaling the GUI for lower resolution screens :)

**Comment by dariomanesku** [comment]
Problem is fixed here: https://github.com/dariomanesku/cmftStudio/commit/f8e3ad71ac0d57a5d839f689abd50a7240551d8e and binaries are updated.
