### ISSUE TITLE
[Windows] The font is being rendered incorrectly when application window is maximized

### ISSUE THREAD

**Issue by vanderlokken** [dariomanesku/cmftStudio#6]
The screenshot attached below is made on Windows 8 with maximized application window. In non-maximized state everything's OK.
![cmftstudio](https://cloud.githubusercontent.com/assets/2744602/7292830/d0ea4b90-e9a7-11e4-8f77-0b172e3d00a1.png)

**Comment by dariomanesku** [comment]
What is your screen resolution? How does it behave on other render backends (dx9/dx11/ogl) ?
To check the current renderer backed, press 'F1'. To change it, open `cmftStudio.conf`, change the option there and start cmftStudio again.

**Comment by vanderlokken** [comment]
My screen resolution is 1920x1080. Previous screenshot was made with DX9 backend. With DX11 backend the application crashes during loading. With OpenGL backend the font becomes blurry.
Normal window state (OpenGL):
![cmft_ogl_normal](https://cloud.githubusercontent.com/assets/2744602/7293402/73496330-e9ad-11e4-9f58-71053af22ac4.png)
Maximized window state (OpenGL):
![cmft_ogl_maximized](https://cloud.githubusercontent.com/assets/2744602/7293410/875f2846-e9ad-11e4-977e-3b59a2ef688e.png)

**Comment by dariomanesku** [comment]
This is due to scaling that applied to the UI when it's not drawn at 'default' resolution. It is what it is, I won't address this.
