### ISSUE TITLE
Gamma / brightness issues

### ISSUE THREAD

**Issue by vorg** [dariomanesku/cmftStudio#7]
Why are .hdr images so dark by default on OSX?

Tonemapped skybox looks ok-ish but the reflection map and irradiance are too dark. I the example scene I can barely see any IBL diffuse. Here is example with custom texture. Also bloom has very overexposed look (kind of first gen HDR before IBL/PBR), something is not right here.

![screen shot 2015-06-27 at 14 15 47](https://cloud.githubusercontent.com/assets/171001/8392123/313e0560-1cd7-11e5-9a35-5a57e5648b33.jpg)

![screen shot 2015-06-27 at 14 15 38](https://cloud.githubusercontent.com/assets/171001/8392124/33aeeaa8-1cd7-11e5-91ca-94c571d4b920.jpg)

**Comment by vorg** [comment]
Ok, disabling bloom, light adapt and changing gamma to 0.5 helps. Curious why these are defaults..

**Comment by dariomanesku** [comment]
These should be the steps:
1. Load *.hdr environment.
2. Tonemap it. This modifies the skybox in memory, it's not just a shader parameter.
3. Execute radiance and irradiance filter after skybox is tonemapped.
I just checked them, they should work ok. I added this: https://github.com/dariomanesku/cmftStudio/commit/ae1d744bcfbd57bea670473ea4f96be7cb8cd684 just so it's a little more apparent what is going on.

Tonemap operator is the most basic one and the results you can get with it are at best 'ok-ish', unfortunately. I didn't spend much time on it.
Regarding bloom, what would be your advice, how I get a better bloom?

**Comment by vorg** [comment]
Looks like the quality of loaded .hdr image has a big influence too. Followed the steps above with better env map and it all looks great!

![screen shot 2015-06-28 at 14 04 42](https://cloud.githubusercontent.com/assets/171001/8397513/d3630914-1dc5-11e5-93ef-19ba48f5eeec.jpg)
