### ISSUE TITLE
how to compile the shader?

### ISSUE THREAD

**Issue by chena1982** [dariomanesku/cmftStudio#8]
i want to modify some shader, but i don't known how to compile the shader.
it seems that you create shader from the compiled binary code.
can you tell me how to compile the shader?
thanks.

**Comment by dariomanesku** [comment]
Here: https://github.com/dariomanesku/cmftStudio/blob/master/src/common/appconfig.h#L63

To compile shaders (for OpenGL):
```bash
cd src/shaders
make TARGET=4
```
For that to succeed you need to have `shaderc` in place. Shaderc comes with bgfx, compile it there (and put it manually in the necessary dir if necessary).
