### ISSUE TITLE
Correction of the html page here

### ISSUE THREAD

**Issue by Spirou4D** [dariomanesku/cmftStudio#9]
""""""""""""""""""""
Installing
Windows: No installation available. Put the cmftStudio.exe along with cmftStudio.conf in a desired folder and use it from there
Linux: Use make install and make uninstall. This will create /usr/local/bin/cmftStudio and a desktop shortcut.
""""""""""""""""""""

To prevent errors, it's important to correct this, please:
you must change the command with **sudo make linux-install** and **sudo make linux-uninstall** please.

**Comment by dariomanesku** [comment]
https://github.com/dariomanesku/cmftStudio/commit/1c7be1836fbf2f13ab87f6c6a774f89231c2b6ee :+1:
